#ifndef __KSU_UAPI_FEATURE_H
#define __KSU_UAPI_FEATURE_H

enum ksu_feature_id {
    KSU_FEATURE_SU_COMPAT = 0,
    KSU_FEATURE_KERNEL_UMOUNT = 1,
    KSU_FEATURE_SULOG = 2,
    KSU_FEATURE_ADB_ROOT = 3,
    KSU_FEATURE_SELINUX_HIDE = 4,
    XNSU_FEATURE_KERNEL_SPOOF = 5,
    XNSU_FEATURE_NET_ISOLATE = 6,
    XNSU_FEATURE_PATH_HIDE = 7,
    XNSU_FEATURE_VPN_HIDE = 8,
    KSU_FEATURE_WEBVIEW_ZYGOTE_UMOUNT = 9,

    KSU_FEATURE_MAX
};

#endif
