#ifndef __XNSU_UAPI_FEATURE_H
#define __XNSU_UAPI_FEATURE_H

enum xnsu_feature_id {
    XNSU_FEATURE_SU_COMPAT = 0,
    XNSU_FEATURE_KERNEL_UMOUNT = 1,
    XNSU_FEATURE_SULOG = 2,
    XNSU_FEATURE_ADB_ROOT = 3,
    XNSU_FEATURE_SELINUX_HIDE = 4,

    XNSU_FEATURE_MAX
};

#endif
