package com.xinsu.moe.ui.theme.tokens

object BuiltInThemeCatalog {
    private val authoredThemes = (
        curatedThemeBundles() + listOf(moonlitSilverBlue(), sakuraStreetWalk(), seaBreezeSong())
    ).associateBy(ThemeTokenBundle::id)

    /** The stable manifest order used by the gallery, tests and publication guard. */
    val all: List<ThemeTokenBundle> = listOf(
        "ink-white-companions",
        "twin-peach-heartstrings",
        "winter-blue-scarf",
        "dusk-iron-wind",
        "cloud-slope-stars",
        "sakura-street-walk",
        "sakura-crown-overture",
        "golden-eye-cat-courtyard",
        "mint-pull",
        "ink-order-poster",
        "moonlit-silver-blue",
        "cobalt-night-dress",
        "clear-sky-blue-ribbon",
        "windfield-doll",
        "crimson-eye-jump",
        "cream-street-corner",
        "black-rose-stone-court",
        "sea-breeze-song",
        "pink-mist-night-window",
        "frost-white-crimson-eye",
        "blue-flame-cat-shadow",
    ).map(authoredThemes::getValue)

    /** Kept as an explicit pressure subset for targeted visual-regression checks. */
    val pressureThemes: List<ThemeTokenBundle> = all.filter {
        it.id in setOf("moonlit-silver-blue", "sakura-street-walk", "sea-breeze-song")
    }

    fun byId(id: String?): ThemeTokenBundle? = authoredThemes[id]
}

private data class TokenAccents(
    val primary: Long,
    val onPrimary: Long,
    val primaryContainer: Long,
    val onPrimaryContainer: Long,
    val inversePrimary: Long,
    val secondary: Long,
    val onSecondary: Long,
    val secondaryContainer: Long,
    val onSecondaryContainer: Long,
    val tertiary: Long,
    val onTertiary: Long,
    val tertiaryContainer: Long,
    val onTertiaryContainer: Long,
    val focus: Long,
)

private data class TokenCanvas(
    val background: Long,
    val onBackground: Long,
    val surface: Long,
    val onSurface: Long,
    val surfaceVariant: Long,
    val onSurfaceVariant: Long,
    val surfaceContainerLowest: Long,
    val surfaceContainerLow: Long,
    val surfaceContainer: Long,
    val surfaceContainerHigh: Long,
    val surfaceContainerHighest: Long,
    val surfaceBright: Long,
    val surfaceDim: Long,
    val outline: Long,
    val outlineVariant: Long,
    val inverseSurface: Long,
    val inverseOnSurface: Long,
    val error: Long,
    val onError: Long,
    val errorContainer: Long,
    val onErrorContainer: Long,
)

private fun semantic(accents: TokenAccents, canvas: TokenCanvas) = SemanticColorTokens(
    primary = accents.primary,
    onPrimary = accents.onPrimary,
    primaryContainer = accents.primaryContainer,
    onPrimaryContainer = accents.onPrimaryContainer,
    inversePrimary = accents.inversePrimary,
    secondary = accents.secondary,
    onSecondary = accents.onSecondary,
    secondaryContainer = accents.secondaryContainer,
    onSecondaryContainer = accents.onSecondaryContainer,
    tertiary = accents.tertiary,
    onTertiary = accents.onTertiary,
    tertiaryContainer = accents.tertiaryContainer,
    onTertiaryContainer = accents.onTertiaryContainer,
    background = canvas.background,
    onBackground = canvas.onBackground,
    surface = canvas.surface,
    onSurface = canvas.onSurface,
    surfaceVariant = canvas.surfaceVariant,
    onSurfaceVariant = canvas.onSurfaceVariant,
    surfaceContainerLowest = canvas.surfaceContainerLowest,
    surfaceContainerLow = canvas.surfaceContainerLow,
    surfaceContainer = canvas.surfaceContainer,
    surfaceContainerHigh = canvas.surfaceContainerHigh,
    surfaceContainerHighest = canvas.surfaceContainerHighest,
    surfaceBright = canvas.surfaceBright,
    surfaceDim = canvas.surfaceDim,
    outline = canvas.outline,
    outlineVariant = canvas.outlineVariant,
    inverseSurface = canvas.inverseSurface,
    inverseOnSurface = canvas.inverseOnSurface,
    error = canvas.error,
    onError = canvas.onError,
    errorContainer = canvas.errorContainer,
    onErrorContainer = canvas.onErrorContainer,
    scrim = BLACK,
    focus = accents.focus,
)

private fun moonlitSilverBlue() = ThemeTokenBundle(
    id = "moonlit-silver-blue",
    displayNameKey = "theme_moonlit_silver_blue",
    artwork = ThemeArtworkTokens(
        resourceName = "theme_moonlit_silver_blue.jpg",
        width = 1920,
        height = 1080,
        focalPoint = NormalizedPoint(0.35f, 0.48f),
        subjectSafeRect = NormalizedRect(0.2f, 0.16f, 0.43f, 0.64f),
        scaleMode = ArtworkScaleMode.Crop,
        scrimRails = listOf(ScrimRail(ScrimEdge.Bottom, 0.72f, 1f, 0.34f)),
    ),
    light = semantic(
        accents = TokenAccents(
            primary = 0xFF3F5C9EL, onPrimary = WHITE,
            primaryContainer = 0xFFDBE4FFL, onPrimaryContainer = 0xFF001945L,
            inversePrimary = 0xFFAEC2FFL,
            secondary = 0xFF505A76L, onSecondary = WHITE,
            secondaryContainer = 0xFFD8E1FFL, onSecondaryContainer = 0xFF0C1A31L,
            tertiary = 0xFF624B87L, onTertiary = WHITE,
            tertiaryContainer = 0xFFE9DDFFL, onTertiaryContainer = 0xFF1E0C40L,
            focus = 0xFF5A78C0L,
        ),
        canvas = TokenCanvas(
            background = 0xFFF6F7FDL, onBackground = 0xFF1A1C2AL,
            surface = 0xFFFCFCFFL, onSurface = 0xFF1A1C2AL,
            surfaceVariant = 0xFFE4E6F0L, onSurfaceVariant = 0xFF45485CL,
            surfaceContainerLowest = WHITE, surfaceContainerLow = 0xFFF1F2FBL,
            surfaceContainer = 0xFFEBECF7L, surfaceContainerHigh = 0xFFE5E7F3L,
            surfaceContainerHighest = 0xFFDFE1EEL, surfaceBright = 0xFFFCFCFFL,
            surfaceDim = 0xFFDCDEECL, outline = 0xFF767989L, outlineVariant = 0xFFC6C8D6L,
            inverseSurface = 0xFF1A1C2AL, inverseOnSurface = 0xFFF0F1F9L,
            error = 0xFFBA1A1AL, onError = WHITE,
            errorContainer = 0xFFFFDAD6L, onErrorContainer = 0xFF410002L,
        ),
    ),
    dark = semantic(
        accents = TokenAccents(
            primary = 0xFFAEC2FFL, onPrimary = 0xFF122A55L,
            primaryContainer = 0xFF2C4172L, onPrimaryContainer = 0xFFDBE4FFL,
            inversePrimary = 0xFF3F5C9EL,
            secondary = 0xFFB8C4E8L, onSecondary = 0xFF232C44L,
            secondaryContainer = 0xFF39425CL, onSecondaryContainer = 0xFFD8E1FFL,
            tertiary = 0xFFCBB4E8L, onTertiary = 0xFF32204AL,
            tertiaryContainer = 0xFF483863L, onTertiaryContainer = 0xFFE9DDFFL,
            focus = 0xFF9FB8FFL,
        ),
        canvas = TokenCanvas(
            background = 0xFF0E1220L, onBackground = 0xFFE3E6F2L,
            surface = 0xFF141827L, onSurface = 0xFFE3E6F2L,
            surfaceVariant = 0xFF272C40L, onSurfaceVariant = 0xFFBEC3D8L,
            surfaceContainerLowest = 0xFF090C17L, surfaceContainerLow = 0xFF121624L,
            surfaceContainer = 0xFF171B2BL, surfaceContainerHigh = 0xFF212637L,
            surfaceContainerHighest = 0xFF2B3143L, surfaceBright = 0xFF2B3143L,
            surfaceDim = 0xFF090C17L, outline = 0xFF868BA3L, outlineVariant = 0xFF373D52L,
            inverseSurface = 0xFFE3E6F2L, inverseOnSurface = 0xFF262B3BL,
            error = 0xFFFFB4ABL, onError = 0xFF5C1A1AL,
            errorContainer = 0xFF7A2A2AL, onErrorContainer = 0xFFFFDAD6L,
        ),
    ),
    atmosphere = AtmosphereTokens(
        cardOpacity = 0.68f, chromeOpacity = 0.56f, readableOpacity = 0.9f,
        outlineOpacity = 0.34f, glowColor = 0xFF9FB8FFL, glowIntensity = 0.46f,
        localScrimStrength = 0.34f, cornerRadiusDp = 24f, blurRadiusDp = 32f,
        density = ThemeDensity.Comfortable, preferredMode = ThemeModePreference.Dark,
    ),
    provenance = provenance(
        filename = "3C79AF894DA8613CACE6062AF1F9BCB4.jpg",
        hash = "2be9b5f89278f1fee3b5234d094b5b9688f5b2027dad96f27576de0b99dc43a8",
        primary = "月光银蓝",
        secondary = "冷紫瞳色",
        focus = "月缘冷光",
        surface = "深靛制服与夜空",
    ),
)

private fun sakuraStreetWalk() = ThemeTokenBundle(
    id = "sakura-street-walk",
    displayNameKey = "theme_sakura_street_walk",
    artwork = ThemeArtworkTokens(
        resourceName = "theme_sakura_street_walk.jpg",
        width = 1440,
        height = 2570,
        focalPoint = NormalizedPoint(0.72f, 0.52f),
        subjectSafeRect = NormalizedRect(0.5f, 0.1f, 0.96f, 0.94f),
        scaleMode = ArtworkScaleMode.Crop,
        scrimRails = listOf(ScrimRail(ScrimEdge.Start, 0f, 0.36f, 0.26f)),
    ),
    light = semantic(
        accents = TokenAccents(
            primary = 0xFFBF4A72L, onPrimary = WHITE,
            primaryContainer = 0xFFFFD9E3L, onPrimaryContainer = 0xFF3E0A1EL,
            inversePrimary = 0xFFFFB0C8L,
            secondary = 0xFF9C5A72L, onSecondary = WHITE,
            secondaryContainer = 0xFFFFD9E5L, onSecondaryContainer = 0xFF3A0A20L,
            tertiary = 0xFF8A6A3EL, onTertiary = WHITE,
            tertiaryContainer = 0xFFFFDEB0L, onTertiaryContainer = 0xFF2C1A00L,
            focus = 0xFFE675A0L,
        ),
        canvas = TokenCanvas(
            background = 0xFFFFF8FAL, onBackground = 0xFF3A2E33L,
            surface = 0xFFFFFDFEL, onSurface = 0xFF3A2E33L,
            surfaceVariant = 0xFFF3E7ECL, onSurfaceVariant = 0xFF6E5C64L,
            surfaceContainerLowest = WHITE, surfaceContainerLow = 0xFFFEF6F9L,
            surfaceContainer = 0xFFFBEFF4L, surfaceContainerHigh = 0xFFF6E8EFL,
            surfaceContainerHighest = 0xFFF1E2E9L, surfaceBright = 0xFFFFFDFEL,
            surfaceDim = 0xFFF0E2E8L, outline = 0xFFA5949CL, outlineVariant = 0xFFDCCCD4L,
            inverseSurface = 0xFF3A2E33L, inverseOnSurface = 0xFFFDEFF3L,
            error = 0xFFBA1A1AL, onError = WHITE,
            errorContainer = 0xFFFFDAD6L, onErrorContainer = 0xFF410002L,
        ),
    ),
    dark = semantic(
        accents = TokenAccents(
            primary = 0xFFFFB0C8L, onPrimary = 0xFF5A1730L,
            primaryContainer = 0xFF7A3350L, onPrimaryContainer = 0xFFFFD9E3L,
            inversePrimary = 0xFFBF4A72L,
            secondary = 0xFFF0B4C8L, onSecondary = 0xFF4A1F30L,
            secondaryContainer = 0xFF663246L, onSecondaryContainer = 0xFFFFD9E5L,
            tertiary = 0xFFE8C08AL, onTertiary = 0xFF432C08L,
            tertiaryContainer = 0xFF5F441FL, onTertiaryContainer = 0xFFFFDEB0L,
            focus = 0xFFFF8FB0L,
        ),
        canvas = TokenCanvas(
            background = 0xFF1A1417L, onBackground = 0xFFF0E3E8L,
            surface = 0xFF201A1DL, onSurface = 0xFFF0E3E8L,
            surfaceVariant = 0xFF352B30L, onSurfaceVariant = 0xFFD3C1C9L,
            surfaceContainerLowest = 0xFF140F12L, surfaceContainerLow = 0xFF1C161AL,
            surfaceContainer = 0xFF231C20L, surfaceContainerHigh = 0xFF2D242AL,
            surfaceContainerHighest = 0xFF382E34L, surfaceBright = 0xFF3A2F35L,
            surfaceDim = 0xFF140F12L, outline = 0xFF9C8B93L, outlineVariant = 0xFF4A3E44L,
            inverseSurface = 0xFFF0E3E8L, inverseOnSurface = 0xFF2D242AL,
            error = 0xFFFFB4ABL, onError = 0xFF5C1A1AL,
            errorContainer = 0xFF7A2A2AL, onErrorContainer = 0xFFFFDAD6L,
        ),
    ),
    atmosphere = AtmosphereTokens(
        cardOpacity = 0.74f, chromeOpacity = 0.62f, readableOpacity = 0.92f,
        outlineOpacity = 0.28f, glowColor = 0xFFFF8FB0L, glowIntensity = 0.34f,
        localScrimStrength = 0.26f, cornerRadiusDp = 28f, blurRadiusDp = 28f,
        density = ThemeDensity.Airy, preferredMode = ThemeModePreference.Light,
    ),
    provenance = provenance(
        filename = "1D9051BB0C9DB757AFD78189EC5BEF30.jpg",
        hash = "552e4107e78892cdf04b5f90b1274f202a3fe0b558367b65bd6daf6facb109bc",
        primary = "樱花粉",
        secondary = "瞳色暖粉",
        focus = "春日高光",
        surface = "深蓝制服与街道阴影",
    ),
)

private fun seaBreezeSong() = ThemeTokenBundle(
    id = "sea-breeze-song",
    displayNameKey = "theme_sea_breeze_song",
    artwork = ThemeArtworkTokens(
        resourceName = "theme_sea_breeze_song.jpg",
        width = 944,
        height = 1667,
        focalPoint = NormalizedPoint(0.52f, 0.62f),
        subjectSafeRect = NormalizedRect(0.25f, 0.28f, 0.79f, 0.98f),
        scaleMode = ArtworkScaleMode.Crop,
        scrimRails = listOf(ScrimRail(ScrimEdge.Top, 0f, 0.24f, 0.28f)),
    ),
    light = semantic(
        accents = TokenAccents(
            primary = 0xFF0150CFL, onPrimary = WHITE,
            primaryContainer = 0xFFD5E3FFL, onPrimaryContainer = 0xFF001B3FL,
            inversePrimary = 0xFFA7C9FFL,
            secondary = 0xFF17608AL, onSecondary = WHITE,
            secondaryContainer = 0xFFC6E7FFL, onSecondaryContainer = 0xFF001E2DL,
            tertiary = 0xFFA33A44L, onTertiary = WHITE,
            tertiaryContainer = 0xFFFFDADBL, onTertiaryContainer = 0xFF40000AL,
            focus = 0xFF0871E4L,
        ),
        canvas = TokenCanvas(
            background = 0xFFF5FAFFL, onBackground = 0xFF152432L,
            surface = 0xFFFCFDFFL, onSurface = 0xFF152432L,
            surfaceVariant = 0xFFDCEBF4L, onSurfaceVariant = 0xFF3E4A52L,
            surfaceContainerLowest = WHITE, surfaceContainerLow = 0xFFEEF7FDL,
            surfaceContainer = 0xFFE7F2F9L, surfaceContainerHigh = 0xFFDEEBF3L,
            surfaceContainerHighest = 0xFFD5E5EFL, surfaceBright = 0xFFFCFDFFL,
            surfaceDim = 0xFFD5E4EDL, outline = 0xFF6F7D86L, outlineVariant = 0xFFBDC9D1L,
            inverseSurface = 0xFF152432L, inverseOnSurface = 0xFFEFF5FFL,
            error = 0xFFBA1A1AL, onError = WHITE,
            errorContainer = 0xFFFFDAD6L, onErrorContainer = 0xFF410002L,
        ),
    ),
    dark = semantic(
        accents = TokenAccents(
            primary = 0xFFA9C7FFL, onPrimary = 0xFF002F67L,
            primaryContainer = 0xFF00459CL, onPrimaryContainer = 0xFFD8E2FFL,
            inversePrimary = 0xFF0150CFL,
            secondary = 0xFF8FD0FFL, onSecondary = 0xFF00344DL,
            secondaryContainer = 0xFF01506FL, onSecondaryContainer = 0xFFC6E7FFL,
            tertiary = 0xFFFFB3B7L, onTertiary = 0xFF5D1120L,
            tertiaryContainer = 0xFF7D2936L, onTertiaryContainer = 0xFFFFDADBL,
            focus = 0xFF6FC2E6L,
        ),
        canvas = TokenCanvas(
            background = 0xFF071725L, onBackground = 0xFFD7E6F5L,
            surface = 0xFF0D1E2CL, onSurface = 0xFFD7E6F5L,
            surfaceVariant = 0xFF233440L, onSurfaceVariant = 0xFFBDC8D2L,
            surfaceContainerLowest = 0xFF031019L, surfaceContainerLow = 0xFF0B1B27L,
            surfaceContainer = 0xFF10232FL, surfaceContainerHigh = 0xFF192D3AL,
            surfaceContainerHighest = 0xFF243845L, surfaceBright = 0xFF2A3F4DL,
            surfaceDim = 0xFF031019L, outline = 0xFF86939DL, outlineVariant = 0xFF344955L,
            inverseSurface = 0xFFD7E6F5L, inverseOnSurface = 0xFF243443L,
            error = 0xFFFFB4ABL, onError = 0xFF5C1A1AL,
            errorContainer = 0xFF7A2A2AL, onErrorContainer = 0xFFFFDAD6L,
        ),
    ),
    atmosphere = AtmosphereTokens(
        cardOpacity = 0.7f, chromeOpacity = 0.5f, readableOpacity = 0.9f,
        outlineOpacity = 0.3f, glowColor = 0xFF6FC2E6L, glowIntensity = 0.38f,
        localScrimStrength = 0.28f, cornerRadiusDp = 24f, blurRadiusDp = 26f,
        density = ThemeDensity.Airy, preferredMode = ThemeModePreference.Light,
    ),
    provenance = provenance(
        filename = "C992E5F52EC5B0BFE25175807ED80406.jpg",
        hash = "60d7c40a213f6051ff63f585df4c3d9698bcdcac209000f93d26dc344e4740f2",
        primary = "海天青",
        secondary = "红色领结",
        focus = "水光亮青",
        surface = "深海蓝与衣装阴影",
    ),
)

private fun provenance(
    filename: String,
    hash: String,
    primary: String,
    secondary: String,
    focus: String,
    surface: String,
) = ThemeProvenance(
    sourceFilename = filename,
    sha256 = hash,
    rightsStatus = ThemeRightsStatus.UserProvidedPendingPublicationConfirmation,
    roleNotes = mapOf(
        "primary" to primary,
        "secondary" to secondary,
        "focus" to focus,
        "surface" to surface,
    ),
    pipelineVersion = "1.0.0",
    contrastValidated = true,
)

private const val WHITE = 0xFFFFFFFFL
private const val BLACK = 0xFF000000L
